import {
  Database,
  BarChart3,
  FileBarChart,
  Brain,
  Filter,
  Cog,
  Cpu,
  Waves,
  Braces,
  Image,
  Zap,
  File,
  Cloud,
  Radio,
  Network,
  DownloadCloud,
  Copy,
  Plug,
  Webhook,
  Share2,
  AppWindow,
  Server,
  HardDrive,
  MemoryStick,
  Workflow,
  Clock,
  Layers,
  KeyRound,
  Users,
  ShieldCheck,
  Box,
  ScrollText,
  Terminal,
  Table,
  GitBranch,
  Key,
  type LucideIcon,
} from 'lucide-react'

// Named icon registry — a SceneSpec references an icon by a short string (so the spec
// stays serializable/render-free), and only the icons mapped here are bundled. Thin
// line icons match the reference figures. Add a name here to make it available.
const icons: Record<string, LucideIcon> = {
  database: Database,
  barChart: BarChart3,
  report: FileBarChart,
  brain: Brain,
  funnel: Filter,
  gears: Cog,
  engine: Cpu,
  lake: Waves,
  json: Braces,
  image: Image,
  streaming: Zap,
  file: File,
  cloud: Cloud,
  stream: Radio,
  federation: Network,
  autoload: DownloadCloud,
  copy: Copy,
  plug: Plug,
  api: Webhook,
  share: Share2,
  app: AppWindow,
  server: Server,
  disk: HardDrive,
  memory: MemoryStick,
  workflow: Workflow,
  clock: Clock,
  layers: Layers,
  key: KeyRound,
  users: Users,
  shield: ShieldCheck,
  box: Box,
  scroll: ScrollText,
  terminal: Terminal,
  table: Table, // fact / dimension tables
  branch: GitBranch, // schema branches / SCD versions
  surrogateKey: Key, // surrogate / natural keys
}

export const getIcon = (name?: string): LucideIcon | undefined => (name ? icons[name] : undefined)
